version: '3'
services:
  rails:
    build:
      context: ./rails
    command: bash -c "bundle install && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - ./rails:/myapp
      - bundle:/usr/local/bundle
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
  db:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: rails_practice
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
volumes:
  mysql_data:
  bundle: